kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "tutorialmanager.fullname" . }}-configmap
  labels:
    {{- include "tutorialmanager.labels" . | nindent 4 }}
data:
  application-prod.yml: |
    {{- toYaml .Values.appBackend.config | nindent 4 }}
