{{- if .Values.appBackend.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "tutorialmanager.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"        
    userAssignedIdentityID: {{ .Values.appBackend.azureKeyVault.userAssignedIdentityID }} 
    keyvaultName: {{ .Values.appBackend.azureKeyVault.keyvaultName }} 
    objects:  |
      array:
        - |
          objectName: {{ .Values.appBackend.mysqlPassword }}
          objectType: secret
        - |
          objectName: {{ .Values.appBackend.redisPassword }}
          objectType: secret
    tenantId: {{ .Values.appBackend.azureKeyVault.tenantId }} 
{{- end }}
