lab2:
  tutorial-manager:
    domain-manager:
      cacheExpirationSec: 60
      wordBlackList:
        - hacker
        - crack
    infra-cache:
      # Can be mem, redis
      provider: mem

spring:
  application:
    name: Tutorial Manager

  datasource:
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    com.lab2.tutorialmanager: DEBUG
    org.hibernate.SQL: DEBUG
